
services:
  db:
    container_name: postagram_db
    image: postgres:14.3-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=unicorn
      - POSTGRES_PASSWORD=wCh29&HE&T83
      - POSTGRES_DB=nyatidb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    container_name: postagram_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn UnicornRoot.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      - db

volumes:
  uploads_volume:
  postgres_data:
