# Generated by Django 4.1 on 2024-11-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterModelTable(
            name='order',
            table='core.order',
        ),
    ]
